imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true, api: 2.4 }
    templating:
        engines:         ['twig']
        assets_version:  v71
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: "WOVIE_SESSID"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SeklMainFoundationBundle::Form/fields.html.twig'
    globals:
        mailHeader: %slmn_main_userbundle.mail.subject%
        piwikUrl: %slmn_main_userbundle.piwik.url%
        piwikSiteId: %slmn_main_userbundle.piwik.site_id%
        amazonAffiliateUs: %slmn_wovie_mainbundle.amazon_affiliate_trackingid.us%
        amazonAffiliateDe: %slmn_wovie_mainbundle.amazon_affiliate_trackingid.de%
        stripePublishableKey: %slmn_wovie_mainbundle.stripe.publishable_key%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "SLMNWovieMainBundle", "SeklMainFoundationBundle" ]
    #java: /usr/bin/java
    filters:
        jpegoptim:
            bin: /usr/bin/jpegoptim
            strip_all: true
            max: 90
        compass:
            apply_to: "\.sass"
        uglifyjs2:
            node: "%nodeBin%"
            bin: "%kernel.root_dir%/Resources/node_modules/.bin/uglifyjs"
        uglifycss:
            node: "%nodeBin%"
            bin: "%kernel.root_dir%/Resources/node_modules/.bin/uglifycss"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/wovie'
            lazy:     true
    producers:
        create_activity:
            connection:       default
            exchange_options: { name: 'create-activity', type: direct }
    consumers:
        create_activity:
            connection:       default
            exchange_options: { name: 'create-activity', type: direct }
            queue_options:    { name: 'create-activity' }
            callback:         wovie.create_activity_service

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
        cache:
            type: predis
            alias: cache
            dsn: redis://localhost/1
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
        session:
            type: predis
            alias: session
            dsn: redis://localhost/2
    session:
        client: session
        use_as_default: true
        ttl: 1800
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: [default]
        query_cache:
            client: cache
            entity_manager: default

fos_elastica:
    clients:
        default: { host: %elasticsearch.host%, port: %elasticsearch.port% }
    indexes:
        wovie:
            client: default
            types:
                Media:
                    mappings:
                        title: { boost: 10, analyzer: snowball }
                        description: { boost: 5, analyzer: snowball }
                        countries: ~
                        createdAt: { type: date }
                        lastUpdatedAt: { type: date }
                        mediaType: ~
                        releaseYear: ~
                        finalYear: ~
                        runtime: ~
                        writtenBy: ~
                        genres: ~
                        numberOfEpisodes: ~
                        rating: ~
                        favorite: ~
                        createdBy:
                            type: "nested"
                            properties:
                                id: ~
                    persistence:
                        driver: orm
                        model: SLMN\Wovie\MainBundle\Entity\Media
                        provider: ~
                        listener: ~
                        finder: ~
