security:
    encoders:
        Sekl\Main\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: SeklMainUserBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            remember_me:
                name: WOVIE_REMEMBERME
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path:     /
                domain:   ~
            pattern: ^/
            form_login:
                default_target_path: /
                use_referer: true
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recover, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bundles, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/image/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sitemap, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }