# Public
slmn_wovie_public_requestNewPassword:
    path:   /recover
    defaults: { _controller: SLMNWovieMainBundle:Public:requestNewPassword }
    methods:  [GET, POST]

slmn_wovie_public_redeemNewPassword:
    path:   /recover/{token}
    defaults: { _controller: SLMNWovieMainBundle:Public:redeemNewPassword }
    methods:  [GET, POST]
    requirements:
        token: "^[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890]{50}+$"

# User
slmn_wovie_user_dashboard:
    pattern:  /
    defaults: { _controller: SLMNWovieMainBundle:User:dashboard }
    methods:  [GET]
slmn_wovie_user_movie_add:
    pattern:  /add/
    defaults: { _controller: SLMNWovieMainBundle:User:addMovie }
    methods:  [GET, POST]
slmn_wovie_user_movie_details:
    pattern:  /{id}/
    defaults: { _controller: SLMNWovieMainBundle:User:dashboard }
    methods:  [GET]
    requirements:
        id: \d+
slmn_wovie_user_search:
    pattern:  /search
    defaults: { _controller: SLMNWovieMainBundle:User:search }
    methods:  [GET]

# Actions
slmn_wovie_action_search_external:
    pattern: /action/search-external/{query}
    defaults: { _controller: SLMNWovieMainBundle:Action:searchExternal }
    methods: [GET]
    # TODO: requirements: …

# System
login:
    path:   /login
    defaults:  { _controller: SLMNWovieMainBundle:User:login }
    methods:  [GET]
login_check:
    path:   /login_check
    methods:  [POST]
logout:
    path:   /logout
    methods:  [GET]