# Public
slmn_wovie_public_requestNewPassword:
    path:   /recover
    defaults: { _controller: SLMNWovieMainBundle:Public:requestNewPassword }
    methods:  [GET, POST]
slmn_wovie_public_redeemNewPassword:
    path:   /recover/{token}
    defaults: { _controller: SLMNWovieMainBundle:Public:redeemNewPassword }
    methods:  [GET, POST]
    requirements:
        token: "^[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890]{50}+$"
slmn_wovie_public_profile:
    path:   /u/{username}/
    defaults: { _controller: SLMNWovieMainBundle:Public:profile }
    methods:  [GET]
    requirements:
        username: "^[a-zA-Z0-9]+$"
slmn_wovie_public_profile_followers:
    path:   /u/{username}/followers
    defaults: { _controller: SLMNWovieMainBundle:Public:profileFollowers } # TODO: Create action
    methods:  [GET]
    requirements:
        username: "^[a-zA-Z0-9]+$"
slmn_wovie_public_profile_followings:
    path:   /u/{username}/follows
    defaults: { _controller: SLMNWovieMainBundle:Public:profileFollowings } # TODO: Create action
    methods:  [GET]
    requirements:
        username: "^[a-zA-Z0-9]+$"
slmn_wovie_public_media_details:
    pattern:  /m/{id}/
    defaults: { _controller: SLMNWovieMainBundle:Public:detailsMedia }
    methods:  [GET]
    requirements:
        id: \d+

# User
slmn_wovie_user_dashboard:
    pattern:  /
    defaults: { _controller: SLMNWovieMainBundle:User:dashboard }
    methods:  [GET]
slmn_wovie_user_movie_shelf:
    pattern:  /library/
    defaults: { _controller: SLMNWovieMainBundle:User:shelf }
    methods:  [GET]
    options:
      expose: true
slmn_wovie_user_movie_add:
    pattern:  /add/
    defaults: { _controller: SLMNWovieMainBundle:User:addMovie }
    methods:  [GET, POST]
slmn_wovie_user_movie_edit:
    pattern:  /edit/{id}/
    defaults: { _controller: SLMNWovieMainBundle:User:editMovie }
    methods:  [GET, POST]
    requirements:
        id: \d+
slmn_wovie_user_movie_details:
    pattern:  /details/{id}/
    defaults: { _controller: SLMNWovieMainBundle:User:detailsMedia }
    methods:  [GET]
    requirements:
        id: \d+
slmn_wovie_user_activity:
    pattern:  /activity/
    defaults: { _controller: SLMNWovieMainBundle:User:activity }
    methods:  [GET]
slmn_wovie_user_search:
    pattern:  /search
    defaults: { _controller: SLMNWovieMainBundle:User:search }
    methods:  [GET]
slmn_wovie_user_feedback:
    pattern:  /feedback/
    defaults: { _controller: SLMNWovieMainBundle:User:feedback }
    methods:  [GET, POST]
slmn_wovie_user_settings_general:
    pattern:  /settings/general/
    defaults: { _controller: SLMNWovieMainBundle:User:settingsGeneral }
    methods:  [GET, POST]
slmn_wovie_user_settings_profile:
    pattern:  /settings/account/
    defaults: { _controller: SLMNWovieMainBundle:User:settingsProfile }
    methods:  [GET, POST]
slmn_wovie_user_settings_billing:
    pattern:  /settings/billing/
    defaults: { _controller: SLMNWovieMainBundle:User:settingsBilling }
    methods:  [GET, POST]

# Actions
slmn_wovie_action_ajax_search_external:
    pattern: /action/ajax/search-external.html
    defaults: { _controller: SLMNWovieMainBundle:Action:searchExternal }
    methods: [GET]
    options:
        expose: true
slmn_wovie_actions_ajax_fetch_description:
    pattern: /action/ajax/fetch-description.html
    defaults: { _controller: SLMNWovieMainBundle:Action:fetchDescription }
    methods: [GET]
    options:
      expose: true
slmn_wovie_actions_ajax_watchedit:
    pattern: /action/ajax/watchedit.json
    defaults: { _controller: SLMNWovieMainBundle:Action:watchedIt }
    methods: [POST]
    options:
      expose: true
    requirements:
        id: \d+
slmn_wovie_actions_ajax_watcheditnot:
    pattern: /action/ajax/watcheditnot.json
    defaults: { _controller: SLMNWovieMainBundle:Action:watchedItNot }
    methods: [POST]
    options:
      expose: true
    requirements:
        id: \d+
slmn_wovie_actions_ajax_media_delete:
    pattern: /action/ajax/media/delete/
    defaults: { _controller: SLMNWovieMainBundle:Action:mediaDelete }
    methods: [POST]
    options:
      expose: true
slmn_wovie_actions_ajax_user_follow:
    pattern: /action/ajax/user/follow.json
    defaults: { _controller: SLMNWovieMainBundle:Action:userFollow }
    methods: [POST]
    options:
      expose: true
    requirements:
        userId: \d+
slmn_wovie_actions_ajax_user_defollow:
    pattern: /action/ajax/user/unfollow.json
    defaults: { _controller: SLMNWovieMainBundle:Action:userDefollow }
    methods: [POST]
    options:
      expose: true
    requirements:
        userId: \d+
slmn_wovie_actions_ajax_infinite_activity:
    pattern: /action/ajax/infinite/activity/{page}.html
    defaults: { _controller: SLMNWovieMainBundle:Action:infiniteActivity }
    methods: [GET]
    requirements:
        page: \d+

# Frames
slmn_wovie_action_frames_choose_episode:
    pattern: /frame/choose-episode/{id}/
    defaults: { _controller: SLMNWovieMainBundle:Frame:chooseEpisode }
    methods: [GET]
    requirements:
        id: \d+

# Image
slmn_wovie_image_coverImage:
    pattern: /image/public/cover/{freebaseId}.jpg
    host: "{cdn}"
    defaults: { _controller: SLMNWovieMainBundle:Image:coverImage, cdn: "%slmn_wovie_mainbundle.cdn%" }
    methods: [GET]
    requirements:
        cdn: "%slmn_wovie_mainbundle.cdn%|%slmn_wovie_mainbundle.domain%"
        freebaseId: "^\/m\/[0-9a-z_]{2,10}$"

# Webhook
slmn_wovie_webhook_stripe:
    pattern: /webhook/stripe
    defaults: { _controller: SLMNWovieMainBundle:Webhook:stripe }
    methods: [POST]

# JS ASSETS
slmn_wovie_js_zeroClipboardSwf:
    pattern: /bundles/slmnwoviemain/swf/ZeroClipboard.swf
    host: "{cdn}"
    defaults: { cdn: "%slmn_wovie_mainbundle.cdn%" }
    methods: [GET]
    options:
      expose: true
    requirements:
        cdn: "%slmn_wovie_mainbundle.cdn%|%slmn_wovie_mainbundle.domain%"

# Sitemap
slmn_wovie_sitemap_main:
    pattern: /sitemap.{_format}
    defaults: { _controller: SLMNWovieMainBundle:Sitemap:main, _format: "xml" }

# System
login:
    path:   /login
    defaults:  { _controller: SLMNWovieMainBundle:User:login }
    methods:  [GET]
login_check:
    path:   /login_check
    methods:  [POST]
logout:
    path:   /logout
    methods:  [GET]