parameters:
    slmn_wovie_main.service.media_api.class: SLMN\Wovie\MainBundle\MediaApi\MediaApi
    slmn_wovie_main.form.type.media.class: SLMN\Wovie\MainBundle\Form\Type\MediaType

services:
    media_api:
        class: %slmn_wovie_main.service.media_api.class%
    slmn_wovie_main.form.type.media:
        class: %slmn_wovie_main.form.type.media.class%
        tags:
            - { name: form.type, alias: media }