parameters:
    slmn_wovie_main.service.media_api.class: SLMN\Wovie\MainBundle\MediaApi\MediaApi
    slmn_wovie_main.twig.slmn_wovie_extension.class: SLMN\Wovie\MainBundle\Twig\SlmnWovieExtension
    slmn_wovie_main.form.type.media.class: SLMN\Wovie\MainBundle\Form\Type\MediaType
    slmn_wovie_main.form.type.feedback.class: SLMN\Wovie\MainBundle\Form\Type\FeedbackType

services:
    slmn_wovie_cache:
        class: Doctrine\Common\Cache\%slmn_wovie_mainbundle.cache.type%
    media_api:
        class: %slmn_wovie_main.service.media_api.class%
        arguments: [@kernel, "%slmn_wovie_mainbundle.google_api_key%", @slmn_wovie_cache]
    slmn_wovie_main.twig.slmn_wovie_extension:
        class: %slmn_wovie_main.twig.slmn_wovie_extension.class%
        arguments: [@doctrine.orm.entity_manager, @security.context, @slmn_wovie_cache]
        tags:
            - { name: twig.extension }
    slmn_wovie_main.form.type.media:
        class: %slmn_wovie_main.form.type.media.class%
        tags:
            - { name: form.type, alias: media }
    slmn_wovie_main.form.type.feedback:
        class: %slmn_wovie_main.form.type.feedback.class%
        tags:
            - { name: form.type, alias: feedback }
