parameters:
    slmn_wovie_main.service.media_api.class: SLMN\Wovie\MainBundle\MediaApi\MediaApi
    slmn_wovie_main.twig.slmn_wovie_extension.class: SLMN\Wovie\MainBundle\Twig\SlmnWovieExtension
    slmn_wovie_main.form.type.media.class: SLMN\Wovie\MainBundle\Form\Type\MediaType
    slmn_wovie_main.form.type.feedback.class: SLMN\Wovie\MainBundle\Form\Type\FeedbackType
    slmn_wovie_main.form.type.editUser.class: SLMN\Wovie\MainBundle\Form\Type\EditUserType
    slmn_wovie_main.form.type.generalSettings.class: SLMN\Wovie\MainBundle\Form\Type\GeneralSettingsType
    slmn_wovie_main.form.type.profile.class: SLMN\Wovie\MainBundle\Form\Type\ProfileType
    slmn_wovie_main.userOption.class: SLMN\Wovie\MainBundle\UserOption
    slmn_wovie_main.session_fix.class: SLMN\Wovie\MainBundle\SessionFix

services:
    # System
    slmn_wovie_main.session_fix:
        class: %slmn_wovie_main.session_fix.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    slmn_wovie_cache:
        class: Doctrine\Common\Cache\%slmn_wovie_mainbundle.cache.type%
    media_api:
        class: %slmn_wovie_main.service.media_api.class%
        arguments: [@kernel, @doctrine.orm.entity_manager, "%slmn_wovie_mainbundle.google_api_key%", @slmn_wovie_cache, @userOption]
    slmn_wovie_main.twig.slmn_wovie_extension:
        class: %slmn_wovie_main.twig.slmn_wovie_extension.class%
        arguments: [@doctrine.orm.entity_manager, @security.context, @slmn_wovie_cache, @userOption, @router]
        tags:
            - { name: twig.extension }
    userOption:
        class:  %slmn_wovie_main.userOption.class%
        arguments:
            em: @doctrine.orm.entity_manager
            context: @security.context
    # Forms
    slmn_wovie_main.form.type.media:
        class: %slmn_wovie_main.form.type.media.class%
        tags:
            - { name: form.type, alias: media }
    slmn_wovie_main.form.type.feedback:
        class: %slmn_wovie_main.form.type.feedback.class%
        tags:
            - { name: form.type, alias: feedback }
    slmn_wovie_main.form.type.editUser:
        class: %slmn_wovie_main.form.type.editUser.class%
        tags:
            - { name: form.type, alias: editUser }
    slmn_wovie_main.form.type.generalSettings:
        class: %slmn_wovie_main.form.type.generalSettings.class%
        tags:
            - { name: form.type, alias: generalSettings }
    slmn_wovie_main.form.type.profile:
        class: %slmn_wovie_main.form.type.profile.class%
        tags:
            - { name: form.type, alias: profile }

